# Generated by Django 3.2.4 on 2022-03-11 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220311_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followings',
            old_name='followers',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='followings',
            old_name='following',
            new_name='user_followed',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 20, 22, 30, 391418)),
        ),
    ]
