# Generated by Django 3.2.4 on 2022-03-12 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20220312_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='number_likes',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 21, 56, 31, 476773)),
        ),
    ]
