# Generated by Django 3.2.4 on 2022-03-13 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20220313_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='following',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 9, 27, 48, 719817)),
        ),
    ]
